### ISSUE TITLE
I've got an error while installing 

### ISSUE THREAD

**Issue by sharifiniax** [SamadiPour/bonbast#23]
I wanted to install it and my OS is Ubuntu 18.04 and here's the error :

Collecting bs4
  Using cached bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 12, in <module>
          import setuptools.version
        File "/usr/lib/python3/dist-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 77, in <module>
          __import__('pkg_resources.extern.packaging.requirements')
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
          from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
        File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
        File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
        File "/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py", line 43, in load_module
          __import__(extant)
        File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 943, in <module>
          collections.MutableMapping.register(ParseResults)
      AttributeError: module 'collections' has no attribute 'MutableMapping'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by SamadiPour** [comment]
What version of python are you using?
The problem is not with this package specifically, but with one of its dependencies. It fails during installation. Updating pip, wheel, and setuptools "might" help:

```
pip3 install --upgrade pip wheel setuptools
```

**Comment by sharifiniax** [comment]
Ok, thanks, after it had upgraded the pip, wheel and setuptools, Bonbast installed successfully 
but I still have an error : (python --version == Python 3.10.10)

$ python -m bonbast 
Traceback (most recent call last):
  File "/home/mk/.local/lib/python3.10/site-packages/bonbast/main.py", line 10, in <module>
    from .server import *
  File "/home/mk/.local/lib/python3.10/site-packages/bonbast/server.py", line 5, in <module>
    import requests
  File "/usr/local/lib/python3.10/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 40, in <module>
    from .util.ssl_ import (
  File "/usr/lib/python3/dist-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/usr/lib/python3/dist-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/usr/lib/python3/dist-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mk/.local/lib/python3.10/site-packages/bonbast/__main__.py", line 1, in <module>
    from bonbast import main
  File "/home/mk/.local/lib/python3.10/site-packages/bonbast/main.py", line 17, in <module>
    from models import *
ModuleNotFoundError: No module named 'models'

**Comment by SamadiPour** [comment]
Unfortunately, I can't reproduce your issue with Python 3.10.10
I tried it with its docker like this, and everything seems fine.
```
docker run -it --rm python:3.10.10-bullseye sh
```

<img width="903" alt="image" src="https://user-images.githubusercontent.com/24422125/227962126-7a8c1de7-27f4-4829-8443-0f409183f9be.png">


I will leave this issue open. Let's see if anyone else knows what the problem is.

**Comment by sharifiniax** [comment]
Great. thanks for your support.
